name: Pipeline teste

# evento que aciona a pipeline
on: 
    push:
        branches:
            - dev

# o que a pipeline deve fazer quando for acionada            
jobs:
    validar-push-dev:  
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 
            
            - name: Checkout index 
              run: test -f index.html
    